import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main>
          <Header />
          {children}
        </main>

        {/* <SanityLive /> */}
      </body>
    </html>
  );
}
